<?php

class foster_child_readme_txt
{

    private $readme;
    private $child;
    private $parent_theme;
    private $theme_json_theme;

    function __construct($child, $parent_theme, $theme_json_theme) {
        $this->child = $child;
        $this->parent_theme = $parent_theme;
        $this->theme_json_theme = $theme_json_theme;
        $this->readme = $this->get_readme_txt();

    }

    function get_contributors() {
        //print_r( $this->parent_theme);
        //print_r( $this->theme_json_theme );
        return 'bobbingwide';
    }

    function get_description() {
       // $description = " Description: ";
        $description = sprintf(__("Child theme of %s with theme.json from %s"),
            $this->parent_theme->display('Name'),
            $this->theme_json_theme->display('Name')
        );
        return $description;
    }

    function get_contents()
    {
        $contents = implode(PHP_EOL, $this->readme);
        return $contents;
    }

    function get_readme_txt() {

        $readme = [];
        $readme[] = "=== " . $this->child . " ===";
        $readme[] = 'Contributors: ' . $this->get_contributors();

        $readme[] = 'Requires at least: 5.9';
        $readme[] = 'Tested up to: 5.9';
        $readme[] = 'Version: 0.0.0';
        $readme[] = 'Tags: full-site-editing';
        $readme[] = 'License: GPL-2.0+';
        $readme[] = 'License URI: http://www.gnu.org/licenses/gpl-2.0.html';
        $readme[] = '';
        $readme[] = '== Description ==';
        $readme[] = $this->get_description();
        $readme[] = '';
        $readme[] = '== Change Log ==';
        $readme[] = '= 0.0.0 = ';
        $readme[] = '* Added: Generated by foster-child on ' . bw_format_date( null, 'Y-m-d H:i:s');
        $readme[] = '';
        $readme[] = '== Licence ==';
        $readme[] = '';
        $readme[] = $this->child . " is distributed under the terms of the GNU GPL.";
        $readme[] = "
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
";

        return $readme;

    }

/*
=== child-theme ===
Contributors: bobbingwide
Requires at least: 5.9
Tested up to: 5.9
Version: 0.0.0
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html

== Description ==

Description same as in style.css

== Change Log ==
= 0.0.1 =
* Added: Generated by foster-child on yyyy-mm-dd hh:ss

== Licence ==

child-theme is distributed under the terms of the GNU GPL.




*/

}